### ISSUE TITLE
Does the current code only support ubuntu? How to use a pre trained model to concatenate one's own images

### ISSUE THREAD

**Issue by af-doom** [minshu-kim/Neural-Image-Stitching#2]
Hello, thank you very much for your great open-source work. Does the current code only support ubuntu? How to use a pre trained model to concatenate one's own images

**Comment by minshu-kim** [comment]
Our implementation was validated in only the Ubuntu environment.
As a guideline to use the pretrained models, we will commit example codes for stitching of one's images maybe til this month.

**Comment by minshu-kim** [comment]
Sorry for the delay.
Now we have added example codes.

Thanks.
