### ISSUE TITLE
question about the test score ogf NIQE,PIQE and BRISQUE

### ISSUE THREAD

**Issue by HouZhe1** [minshu-kim/Neural-Image-Stitching#3]
Dear repository author:

Thank you very much for your great job with the open-source code.I am writing to inquire about your paper, specifically the comparison of stitching effects in Table 1. Could you please explain how the evaluation scores for NIQE, PIQE, and BRISQUE were obtained? Additionally, would it be possible for you to share the testing code publicly?

Thank you for your time and consideration.

**Comment by minshu-kim** [comment]
We use Matlab [NIQE](https://kr.mathworks.com/help/images/ref/niqe.html), [PIQE](https://www.mathworks.com/help/images/ref/piqe.html), [BRISQUE](https://www.mathworks.com/help/images/ref/brisque.html) with saved stitched images.
Please refer to their official documents.

Thanks.
