### ISSUE TITLE
pre-training model

### ISSUE THREAD

**Issue by wudami** [minshu-kim/Neural-Image-Stitching#5]
Hi, thanks for the open source, is there any other link for pre-training model? Can you share a link for the dataset?

**Comment by minshu-kim** [comment]
You can find Google drive and baidu links of UDIS-D dataset on [this page](https://github.com/nie-lang/UnsupervisedDeepImageStitching). For 2017v MS-COCO,  Please refer to the [official page](https://cocodataset.org/#download).

If you still need the pre-trained models, email me.
minshu.kim26@gmail.com
