### ISSUE TITLE
yours generated synthetic dataset

### ISSUE THREAD

**Issue by one123455** [minshu-kim/Neural-Image-Stitching#6]
Can you provide yours generated synthetic dataset of MS-COCO?

**Comment by minshu-kim** [comment]
We didn't save the dataset because we used on-the-fly dataset generation. However, you can generate and save the same samples as the dataset we used for evaluation using our "eval_enhancing.py" code.

The applied randomness is reproducible due to a fixed seed number.

**Comment by one123455** [comment]
Thank you for your reply. May I ask how the supervised dataset was generated during the first stage of IHN training？
